---
    name: Checkov
    on:
      push:
        branches:
          - master
    jobs:
        checkov-job:
            runs-on: ubuntu-latest
            name: checkov-action
            steps:
              - name: Checkout repo
                uses: actions/checkout@master

              - name: Run Checkov action
                id: checkov
                uses: bridgecrewio/checkov-action@master
                with:
                  directory: tfinfra/
                  external_checks_dir: ckv_custom_checks/  
                  skip_check: CKV_GCP_39, CKV_GCP_30 # optional: skip a specific check_id
                  # quiet: true # optional: display only failed checks
